version: '3.0'

services:
  aplicacao:
    image: mreis08/flask
    environment:
    - 'DB_HOST=banco'
    - 'DB_USER=container'
    - 'DB_PASS=4linux'
    - 'DB_NAME=container'
    ports:
    - '5000:5000'
  banco:
    image: mariadb
    environment:
    - 'MYSQL_ROOT_PASSWORD=Abc123_'
    - 'MYSQL_USER=container'
    - 'MYSQL_PASSWORD=4linux'
    - 'MYSQL_DATABASE=container'
    volumes:
    - 'data:/var/lib/mysql'

volumes:
  data: {} # indica chave de valor vazio
